### ISSUE TITLE
Json Response is Null

### ISSUE THREAD

**Issue by Tetrax-10** [rustyinfinity/StashNfoExporter#2]
![image](https://github.com/rustyinfinity/StashNfoExporter/assets/75513645/8e88da04-e7ee-489e-b954-cbed7c5f83a6)

**Comment by Tetrax-10** [comment]
Its because of i have password protected my stash. How do I solve this?

**Comment by rustyinfinity** [comment]
> Its because of i have password protected my stash. How do I solve this?

Did you add api key in the config.py file ?
<img width="1438" alt="Screenshot 2024-01-24 at 12 36 44 PM" src="https://github.com/rustyinfinity/StashNfoExporter/assets/115462641/a398de2a-3d26-4cb5-a888-4e1af905359d">

**Comment by rustyinfinity** [comment]
Yeah i recreated it must be because you had not added api key in config.

For now i will try to fix that Syntax Warning that should not come. Thanks 

<img width="788" alt="Screenshot 2024-01-24 at 12 45 11 PM" src="https://github.com/rustyinfinity/StashNfoExporter/assets/115462641/3d0ec838-fe7a-4f16-9c27-6e6ea8bb56a9">

**Comment by Tetrax-10** [comment]
Am sry am new to Stash, didnt know api key existed, now it works, thx for the awesome plugin
